name: Nintendo Switch Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Environment
        run: |
          echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
          echo "DEVKITARM=/opt/devkitpro/devkitARM" >> $GITHUB_ENV
          echo "DEVKITA64=/opt/devkitpro/devkitA64" >> $GITHUB_ENV
          echo "/opt/devkitpro/devkitA64/bin" >> $GITHUB_PATH

      - name: Verify Toolchain
        run: |
          ls /opt/devkitpro/cmake/Switch.cmake || { echo "switch.cmake not found"; exit 1; }
          which aarch64-none-elf-gcc
          which make
          which cmake
          which nacptool
          sed -i '/posix_module.c/d' raylib-nx/src/external/glfw/CMakeLists.txt || true
          grep -v "posix_module.c" raylib-nx/src/external/glfw/CMakeLists.txt

      - name: Patch GLFW CMakeLists
        run: |
          if grep -q "posix_module.c" raylib-nx/src/external/glfw/CMakeLists.txt; then
            sed -i '/posix_module.c/d' raylib-nx/src/external/glfw/CMakeLists.txt
            echo "Removed posix_module.c from GLFW CMakeLists.txt"
          else
            echo "posix_module.c not found in GLFW CMakeLists.txt"
          fi

      - name: Build raylib-nx
        run: |
          cd raylib-nx
          mkdir -p cmake-build-switch
          cd cmake-build-switch
          cmake .. -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/Switch.cmake \
                   -DBUILD_EXAMPLES=OFF \
                   -DPLATFORM=NX \
                   -DGLFW_BUILD_POSIX=OFF \
                   -D_GLFW_NX=ON > cmake.log 2>&1 || { cat cmake.log; exit 1; }
          make > make.log 2>&1 || { cat make.log; exit 1; }
          ls -R . || { echo "Failed to list raylib-nx build directory"; exit 1; }
          ls raylib/libraylib.a || { echo "libraylib.a not found"; exit 1; }
          cp raylib/libraylib.a /tmp/libraylib.a
          ls /tmp/libraylib.a

      - name: Info
        run: |
          ls -l raylib-nx
          ls -l /tmp/libraylib.a
          ls -lraylib /cmake-build-switch/raylib/include/raylib.h

      - name: Build Switch Game
        run: |
          cp icon.jpg switch-game/icon.jpg
          cd switch-game
          make clean
          make > make.log 2>&1 || { cat make.log; exit 1; }
          ls switch-game.nacp || { echo "switch-game.nacp not found"; exit 1; }
          ls switch-game.nro || { echo "switch-game.nro not found"; exit 1; }

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: switch-game-artifacts
          path: |
            switch-game/switch-game.nro
            switch-game/switch-game.elf
            switch-game/switch-game.nacp