name: Nintendo Switch Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:base-devel
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          pacman -Syy --noconfirm
          pacman -S --noconfirm base-devel sudo git make cmake zstd archlinux-keyring
          pacman-key --init
          pacman-key --populate archlinux
          # Install devkitPro pacman repository
          curl -L https://pkg.devkitpro.org/devkitpro-keyring.pkg.tar.zst -o devkitpro-pacman.pkg.tar.zst
          pacman -U --noconfirm devkitpro-pacman.pkg.tar.zst
          # Install Switch dependencies
          pacman -Syy --noconfirm
          pacman -S --noconfirm switch-libnx switch-portlibs switch-cmake devkitA64

      - name: Set Environment
        run: |
          echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
          echo "DEVKITARM=/opt/devkitpro/devkitARM" >> $GITHUB_ENV
          echo "DEVKITA64=/opt/devkitpro/devkitA64" >> $GITHUB_ENV
          echo "/opt/devkitpro/devkitA64/bin" >> $GITHUB_PATH

      - name: Verify Toolchain
        run: |
          ls /opt/devkitpro/switch.cmake
          which aarch64-none-elf-gcc
          which make

      - name: Build raylib-nx
        run: |
          cd raylib-nx
          mkdir -p cmake-build-switch
          cd cmake-build-switch
          cmake .. -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/switch.cmake -DBUILD_EXAMPLES=OFF
          make
          ls raylib/libraylib.a

      - name: Build Switch Game
        run: |
          cp icon.jpg switch-game/icon.jpg
          cd switch-game
          make clean
          make

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: switch-game-artifacts
          path: |
            switch-game/switch-game.nro