name: Nintendo Switch Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Environment
        run: |
          echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
          echo "DEVKITARM=/opt/devkitpro/devkitARM" >> $GITHUB_ENV
          echo "DEVKITA64=/opt/devkitpro/devkitA64" >> $GITHUB_ENV
          echo "/opt/devkitpro/devkitA64/bin" >> $GITHUB_PATH

      - name: Verify Toolchain
        run: |
          ls /opt/devkitpro/cmake/Switch.cmake || { echo "switch.cmake not found"; exit 1; }
          which aarch64-none-elf-gcc
          which make
          which cmake
          which nacptool

      - name: Build raylib-nx
        run: |
          git clone https://github.com/luizpestana/raylib-nx
          cd raylib-nx
          mkdir -p cmake-build-switch
          cd cmake-build-switch
          cmake .. -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/cmake/Switch.cmake \
                   -DBUILD_EXAMPLES=OFF \
                   -DPLATFORM=NX \
                   -DGLFW_BUILD_POSIX=OFF \
                   -D_GLFW_NX=ON > cmake.log 2>&1 || { cat cmake.log; exit 1; }
          make > make.log 2>&1 || { cat make.log; exit 1; }
          ls -R . || { echo "Failed to list raylib-nx build directory"; exit 1; }
          ls raylib/libraylib.a || { echo "libraylib.a not found"; exit 1; }
          echo "libraylib.a located at: $(pwd)/raylib/libraylib.a"
          ls raylib/include/raylib.h || { echo "raylib.h not found"; exit 1; }
          echo "raylib.h located at: $(pwd)/raylib/include/raylib.h"
          cp raylib/libraylib.a /tmp/libraylib.a
          echo "libraylib.a copied to: /tmp/libraylib.a"
          mkdir -p /tmp/include
          cp -r raylib/include/* /tmp/include/
          echo "raylib/include copied to: /tmp/include"
          ls -l /tmp/include/raylib.h
          ls -l /tmp/libraylib.a

      - name: Patch CMakeLists
        run: |
          if grep -q "posix_module.c" raylib-nx/src/external/glfw/CMakeLists.txt; then
            sed -i '/posix_module.c/d' raylib-nx/src/external/glfw/CMakeLists.txt
            echo "Removed posix_module.c from GLFW CMakeLists.txt"
          else
            echo "posix_module.c not found in GLFW CMakeLists.txt"
          fi

      - name: Verify Makefile
        run: |
          ls Encore/Makefile || { echo "Makefile not found"; exit 1; }
          echo "Makefile located at: Encore/Makefile"
          grep "switch_rules" Encore/Makefile || echo "No switch_rules found in Makefile"

      - name: Build Switch Game
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 1
          max_attempts: 3
          command: |
            cp icon.jpg Encore/icon.jpg
            cd Encore
            make

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: switch-game-artifacts
          path: |
            Encore/Encore.nro
            Encore/Encore.elf
            Encore/Encore.nacp