name: Nintendo Switch Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64:latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Environment
        run: |
          echo "DEVKITPRO=/opt/devkitpro" >> $GITHUB_ENV
          echo "DEVKITARM=/opt/devkitpro/devkitARM" >> $GITHUB_ENV
          echo "DEVKITA64=/opt/devkitpro/devkitA64" >> $GITHUB_ENV
          echo "/opt/devkitpro/devkitA64/bin" >> $GITHUB_PATH

      - name: Verify Toolchain
        run: |
          ls /opt/devkitpro/switch.cmake || { echo "switch.cmake not found"; exit 1; }
          which aarch64-none-elf-gcc
          which make
          which cmake

      - name: Build raylib-nx
        run: |
          cd raylib-nx
          mkdir -p cmake-build-switch
          cd cmake-build-switch
          cmake .. -DCMAKE_TOOLCHAIN_FILE=/opt/devkitpro/switch.cmake -DBUILD_EXAMPLES=OFF
          make
          ls raylib/libraylib.a

      - name: Build Switch Game
        run: |
          cd switch-game
          make clean
          make
          cp icon.jpg switch-game/icon.jpg

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: switch-game-artifacts
          path: |
            switch-game/switch-game.nro